import json
from pathlib import Path
base=Path('C:/Users/ADMIN/Desktop/GameAssetFactory/blender/weapons');r=json.loads((base/'weapon_refinement_report.json').read_text())
lines=['# Weapon readability refinement','', 'Current revisions: Blocky Pistol V3, M4A1 V4, Blocky Shotgun V3. Created through Blender MCP; earlier working versions remain preserved.','', 'The pistol grip now has upright parallel front/back faces, a flat stable heel, and a short integrated shoulder at the frame. Its old slanted strap and shaped toe were removed. Overall weapon bounds are unchanged: 0.273 m long, 0.052 m wide and 0.227 m high. The M4A1 and shotgun guards are widened locally from approximately 31 mm to 36 mm for isometric readability, retaining their continuous welded connections and unchanged overall bounds.','', '| Asset | Tris before / after | Blender | GLB | Side | Isometric | Trigger close-up |','|---|---:|---|---|---|---|---|']
for key,item in r.items():
 b=Path(item['blend']).relative_to(base);g=Path(item['glb']).relative_to(base);p=b.with_suffix('').as_posix()
 lines.append(f"| {key} | {item['before_triangles']} / {item['after_triangles']} | [Blend]({b.as_posix()}) | [GLB]({g.as_posix()}) | [Side]({p}_side.png) | [Isometric]({p}_isometric.png) | [Close-up]({p}_trigger_closeup.png) |")
lines+=['', '[True-scale comparison](weapon_refinement_comparison.png) / [Comparison Blender scene](weapon_refinement_comparison.blend).','', 'Each static body is a single connected manifold mesh; there are no loose vertices, duplicate indexed faces, boundary edges or inconsistent face winding. Shotgun_Pump stays separately animatable and manifold, with its guide-tube clearance and pivot retained.','', 'Materials and the packed 64x64 atlas are unchanged, including the charcoal/cool-gray/cyan palette, mild specular response, nearest sampling and subtle edge highlights. Root and all attachment-marker matrices exactly match the preceding revisions. Identity scale, applied rotations and grip-centered origins remain. Blender +Y forward converts to Godot -Z forward. Runtime object names and folder structure remain consistent.','', 'GLB validation confirms exported triangle counts, bounds, markers, one material and one embedded image per asset. Pistol and M4A1 each use one runtime surface; shotgun has two for its movable pump. Godot gameplay files were not modified. All side/isometric/close-up previews are transparent RGBA.','', 'Measured results: weapon_refinement_report.json, weapon_refinement_preservation.json, weapon_refinement_glb_validation.json. Source: refine_weapon_readability.py, which reuses the preserved construction source and structural cleanup to replace only the requested grip and guard geometry.']
(base/'WEAPON_REFINEMENT.md').write_text('\n'.join(lines)+'\n')
p=base/'README.md';t=p.read_text(encoding='utf-8-sig');t=t.replace('# Blocky weapon family','# Blocky weapon family\n\nLatest readable set: [Pistol V3, M4A1 V4 and Shotgun V3](WEAPON_REFINEMENT.md), with validated GLBs and side/isometric previews.',1);p.write_text(t,encoding='utf-8')
p=base/'WEAPON_STYLE_GUIDE.md';t=p.read_text(encoding='utf-8-sig').replace('(geometry-clean successor: V3)','(geometry-clean successor: V3; current readability revision: V4)');p.write_text(t,encoding='utf-8')
