"""Assemble on the unchanged v2 mesh/rig/animations, validate before Godot."""
import json,struct,copy,math,hashlib
from pathlib import Path
import numpy as np
BASE=Path(__file__).parent
ASSETS=BASE.parents[3]/'game_mobile_3d/assets/characters'
OUT=BASE/'export/draw_d5'
# Shared read/sample utilities only (the D2 executable portion is not run).
exec((BASE/'validate_export_holster_d2.py').read_text().split("p=ASSETS/")[0])
OUT=BASE/'export/draw_d5'
d,b=read(ASSETS/'player_cuboid_animated_v2.glb')
raw,rb=read(OUT/'draw_raw.glb')
meta=json.loads((OUT/'events.json').read_text())
assert len(d['skins'])==1 and len(d['meshes'])==1
assert {n['name'] for n in d['nodes'] if 'mesh' in n}=={'Player_Cuboid_Base'}
names={n['name']:i for i,n in enumerate(d['nodes'])}
assert 'WeaponCarrier' in names and 'Player_Cuboid_Rig' in names
offset=len(b);offset+=(-offset)%4;b+=b'\0'*(offset-len(b));b+=rb
vo=len(d['bufferViews']);ao=len(d['accessors'])
for v in raw['bufferViews']:
    v=copy.deepcopy(v);v['byteOffset']=offset+v.get('byteOffset',0);d['bufferViews'].append(v)
for ac in raw['accessors']:
    ac=copy.deepcopy(ac);ac['bufferView']+=vo;d['accessors'].append(ac)
a=copy.deepcopy(raw['animations'][0]);a['name']='DrawLongGun'
# Only actual authored property paths; rotation_euler becomes glTF rotation.
authored={'Spine':{'rotation'},'Chest':{'rotation'},'Neck':{'rotation'},'Head':{'rotation'},
          'Arm.R':{'rotation','translation'},'Arm.L':{'rotation','translation'},'WeaponCarrier':{'rotation','translation'}}
a['channels']=[c for c in a['channels'] if c['target']['path'] in authored.get(raw['nodes'][c['target']['node']]['name'],set())]
for s in a['samplers']:s['input']+=ao;s['output']+=ao
for c in a['channels']:c['target']['node']=names[raw['nodes'][c['target']['node']]['name']]
a['extras']=meta;d['animations'].append(a)
assert {x['name'] for x in d['animations']}=={'Idle','Run','HolsterLongGun','DrawLongGun'}
samples=json.loads((OUT/'source_samples.json').read_text());C=np.eye(4);C[:3,:3]=[[1,0,0],[0,0,1],[0,-1,0]]
max_pos=max_angle=0.0
for s in samples:
    worlds=sample(d,b,a,s['time'])
    for name,m in s['bones'].items():
        expected=C@np.array(m);actual=worlds[name]
        max_pos=max(max_pos,float(np.linalg.norm(actual[:3,3]-expected[:3,3])))
        cos=(np.trace(actual[:3,:3].T@expected[:3,:3])-1)/2
        max_angle=max(max_angle,math.degrees(math.acos(np.clip(cos,-1,1))))
assert max_pos<.0001 and max_angle<.12,(max_pos,max_angle)
duration=max(float(values(d,b,s['input'])[-1,0]) for s in a['samplers'])
assert abs(duration-13/24)<1e-6
assert all(d['nodes'][c['target']['node']]['name'] in meta['bones'] and c['target']['path']!='scale' for c in a['channels'])
assert not any('camera' in n or 'light' in n or 'rifle' in n['name'].lower() or 'm4a1' in n['name'].lower() for n in d['nodes'])
write(ASSETS/'player_cuboid_animated_v3.glb',d,b)
# Read back output and compare every pre-existing byte range, node and clip.
check,cb=read(ASSETS/'player_cuboid_animated_v3.glb');old,ob=read(ASSETS/'player_cuboid_animated_v2.glb')
assert cb[:len(ob)]==ob
assert all(check[k]==old[k] for k in ['nodes','meshes','skins'])
assert check['animations'][:3]==old['animations']
# A preloaded resource is included by Godot exports without a *.json export
# filter. Keep one generated runtime representation, sourced from Action data.
(ASSETS/'draw_long_gun_events.gd').write_text('extends RefCounted\n## Generated by validate_export_draw_d5.py from Action event_subframes_json.\nconst DATA = '+json.dumps(meta,indent=2)+'\n')
report={'passed':True,'clips':[x['name'] for x in d['animations']],'duration':duration,'authored_channels':authored,
        'lower_tracks':0,'scale_tracks':0,'root_motion':0,'samples':len(samples),'source_max_position_error_m':max_pos,
        'source_max_rotation_error_deg':max_angle,'mesh_rig_idle_run_holster_byte_preserved':True,'events':meta['event_seconds'],
        'export':str(ASSETS/'player_cuboid_animated_v3.glb')}
report['authored_channels']={k:sorted(v) for k,v in authored.items()}
(OUT/'validation.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
